language: node_js
node_js: '7'
cache: yarn
script:
  - npm run test:all
after_success:
  - node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: 2ddbf78ce4d75238ce06f023d710632e1d6f31da4b22cd66c23e9936fa69ca6e
